name: CI test & build

on:
  pull_request:
    branches: [master]

jobs:
  ci:
    name: Test & build
    runs-on: ubuntu-latest
    permissions:
      # This is required for requesting the OIDC JWT
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use local integration action
        uses: ./.github/actions/integration

      # Test the CD configuration
      - name: Get authorization from GCP
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Authorize with GKE cluster
        uses: "google-github-actions/get-gke-credentials@v1"
        with:
          cluster_name: ${{ secrets.GCP_GKE_CLUSTER_NAME }}
          location: eu-central2

      - name: Deploy the code
        run: kubectl get deployments
